services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
    networks:
      - spring1
    volumes:
      - mysqlvol:/var/lib/mysql
  app:
    image: spring-boot-docker
    ports:
      - 8080:8080
    build: .
    networks:
      - spring1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/ecommerce
    depends_on:
      - mariadb
volumes:
  mysqlvol: {}
networks:
  spring1: {}
